
package vista;

import controlador.ControlSistema;

import java.awt.BorderLayout;
import java.awt.Container;

import java.awt.FlowLayout;
import java.awt.GridLayout;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;

import javax.swing.JDialog;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JTextPane;

import modelo.Alumno;
import modelo.Sistema;

/**
 *
 * @author wence
 */
public class VentanaPrincipal
  extends javax.swing.JFrame
  implements Observer
{
  private ControlSistema controlador;

  /** Creates new form VentanaPrincipal */
  private ArrayList<JTextField> datos;

  public VentanaPrincipal()
  {
    initComponents();
    this.controlador=controlador;
    this.setExtendedState(MAXIMIZED_VERT);
    this.setResizable(false);
    this.setTitle("Programa de Gestion de asignaturas");
  }

  public void setControlador(ControlSistema controlador)
  {
    this.controlador = controlador;
  }

  @Override
  public void update(Observable o, Object arg)
  {
    // TODO Implement this method
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents()//GEN-BEGIN:initComponents
  {

    jPanelAlumno = new javax.swing.JPanel();
    jButtonAltaAlumno = new javax.swing.JButton();
    jButtonUbicarAlumno = new javax.swing.JButton();
    jPanelProfesor = new javax.swing.JPanel();
    jButtonAltaProfesor = new javax.swing.JButton();
    jButtonUbicarProfesor = new javax.swing.JButton();
    jPanelCursada = new javax.swing.JPanel();
    jButtonAltaCursada = new javax.swing.JButton();
    jButtonUbicarCursada = new javax.swing.JButton();
    jPanelAsignatura = new javax.swing.JPanel();
    jButtonAltaAsignatura = new javax.swing.JButton();
    jButtonUbicarAsignatura = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextPane1 = new javax.swing.JTextPane();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanelAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder("Alumno"));

    jButtonAltaAlumno.setText("Alta");
    jButtonAltaAlumno.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseClicked(java.awt.event.MouseEvent evt)
      {
        jButtonAltaAlumnoMouseClicked(evt);
      }
    });
    jButtonAltaAlumno.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonAltaAlumnoActionPerformed(evt);
      }
    });

    jButtonUbicarAlumno.setText("Ubicar");

    javax.swing.GroupLayout jPanelAlumnoLayout = new javax.swing.GroupLayout(jPanelAlumno);
    jPanelAlumno.setLayout(jPanelAlumnoLayout);
    jPanelAlumnoLayout.setHorizontalGroup(
      jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelAlumnoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButtonAltaAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
          .addComponent(jButtonUbicarAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanelAlumnoLayout.setVerticalGroup(
      jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelAlumnoLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButtonAltaAlumno)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButtonUbicarAlumno)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanelProfesor.setBorder(javax.swing.BorderFactory.createTitledBorder("Profesor"));

    jButtonAltaProfesor.setText("Alta");
    jButtonAltaProfesor.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonAltaProfesorActionPerformed(evt);
      }
    });

    jButtonUbicarProfesor.setText("Ubicar");

    javax.swing.GroupLayout jPanelProfesorLayout = new javax.swing.GroupLayout(jPanelProfesor);
    jPanelProfesor.setLayout(jPanelProfesorLayout);
    jPanelProfesorLayout.setHorizontalGroup(
      jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelProfesorLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButtonAltaProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
          .addComponent(jButtonUbicarProfesor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanelProfesorLayout.setVerticalGroup(
      jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelProfesorLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButtonAltaProfesor)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButtonUbicarProfesor)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanelCursada.setBorder(javax.swing.BorderFactory.createTitledBorder("Cursada"));

    jButtonAltaCursada.setText("Alta");
    jButtonAltaCursada.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonAltaCursadaActionPerformed(evt);
      }
    });

    jButtonUbicarCursada.setText("Ubicar");

    javax.swing.GroupLayout jPanelCursadaLayout = new javax.swing.GroupLayout(jPanelCursada);
    jPanelCursada.setLayout(jPanelCursadaLayout);
    jPanelCursadaLayout.setHorizontalGroup(
      jPanelCursadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelCursadaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelCursadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButtonAltaCursada, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
          .addComponent(jButtonUbicarCursada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanelCursadaLayout.setVerticalGroup(
      jPanelCursadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelCursadaLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButtonAltaCursada)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButtonUbicarCursada)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanelAsignatura.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignatura"));

    jButtonAltaAsignatura.setText("Alta");
    jButtonAltaAsignatura.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonAltaAsignaturaActionPerformed(evt);
      }
    });

    jButtonUbicarAsignatura.setText("Ubicar");

    javax.swing.GroupLayout jPanelAsignaturaLayout = new javax.swing.GroupLayout(jPanelAsignatura);
    jPanelAsignatura.setLayout(jPanelAsignaturaLayout);
    jPanelAsignaturaLayout.setHorizontalGroup(
      jPanelAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelAsignaturaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButtonAltaAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
          .addComponent(jButtonUbicarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanelAsignaturaLayout.setVerticalGroup(
      jPanelAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelAsignaturaLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButtonAltaAsignatura)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButtonUbicarAsignatura)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jScrollPane1.setViewportView(jTextPane1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jPanelAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(44, 44, 44)
            .addComponent(jPanelProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(44, 44, 44)
            .addComponent(jPanelAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(44, 44, 44)
            .addComponent(jPanelCursada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(jPanelAsignatura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanelCursada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(jPanelProfesor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAlumno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }//GEN-END:initComponents

  private void jButtonAltaAlumnoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAltaAlumnoActionPerformed
  {//GEN-HEADEREND:event_jButtonAltaAlumnoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonAltaAlumnoActionPerformed

  private void jButtonAltaProfesorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAltaProfesorActionPerformed
  {//GEN-HEADEREND:event_jButtonAltaProfesorActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonAltaProfesorActionPerformed

  private void jButtonAltaCursadaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAltaCursadaActionPerformed
  {//GEN-HEADEREND:event_jButtonAltaCursadaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonAltaCursadaActionPerformed

  private void jButtonAltaAsignaturaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAltaAsignaturaActionPerformed
  {//GEN-HEADEREND:event_jButtonAltaAsignaturaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonAltaAsignaturaActionPerformed

  private void jButtonAltaAlumnoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonAltaAlumnoMouseClicked
  {//GEN-HEADEREND:event_jButtonAltaAlumnoMouseClicked
    
    
    JDialog emergente = new JDialog();
    JPanel finalizacion = new JPanel();
    JPanel elementos = new JPanel();
    Container contenedor;
    JButton aceptar, cancelar;
    emergente.setSize(200, 200);
    emergente.setVisible(true);
    contenedor = emergente.getContentPane();
    contenedor.setLayout(new BorderLayout());

    contenedor.add(elementos, BorderLayout.CENTER);
    elementos.setLayout(new GridLayout(4, 3));

    JTextField fieldNombre = new JTextField();
    JTextField fieldDomicilio = new JTextField();
    JTextField fieldMail = new JTextField();

    elementos.add(new JLabel("Descripcion"));
    elementos.add(new JLabel("Campo"));
    elementos.add(new JLabel("Formato"));

    elementos.add(new JLabel("Nombre y Apellido"));
    elementos.add(fieldNombre);
    elementos.add(new JLabel("---"));

    elementos.add(new JLabel("Domicilio"));
    elementos.add(fieldDomicilio);
    elementos.add(new JLabel("---"));

    elementos.add(new JLabel("Mail"));
    elementos.add(fieldMail);
    elementos.add(new JLabel("AAAA@AAAAA"));

    contenedor.add(finalizacion, BorderLayout.SOUTH);
    aceptar = new JButton("Aceptar");
    finalizacion.add(aceptar);
    cancelar = new JButton("Cancelar");
    finalizacion.add(cancelar);
    aceptar.setSize(50, 100);
    cancelar.setSize(50, 100);

    aceptar.addMouseListener(this.controlador);
    
  }//GEN-LAST:event_jButtonAltaAlumnoMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info: javax.swing
                                                            .UIManager
                                                            .getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing
               .UIManager
               .setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util
          .logging
          .Logger
          .getLogger(VentanaPrincipal.class.getName())
          .log(java.util
                   .logging
                   .Level
                   .SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util
          .logging
          .Logger
          .getLogger(VentanaPrincipal.class.getName())
          .log(java.util
                   .logging
                   .Level
                   .SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util
          .logging
          .Logger
          .getLogger(VentanaPrincipal.class.getName())
          .log(java.util
                   .logging
                   .Level
                   .SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util
          .logging
          .Logger
          .getLogger(VentanaPrincipal.class.getName())
          .log(java.util
                   .logging
                   .Level
                   .SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt
        .EventQueue
        .invokeLater(new Runnable()
      {
        public void run()
        {
          Sistema modelo=new Sistema();
          VentanaPrincipal vista=new VentanaPrincipal();
          ControlSistema control= new ControlSistema(vista);
          vista.setControlador(control);
          vista.setVisible(true);
        }
      });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonAltaAlumno;
  private javax.swing.JButton jButtonAltaAsignatura;
  private javax.swing.JButton jButtonAltaCursada;
  private javax.swing.JButton jButtonAltaProfesor;
  private javax.swing.JButton jButtonUbicarAlumno;
  private javax.swing.JButton jButtonUbicarAsignatura;
  private javax.swing.JButton jButtonUbicarCursada;
  private javax.swing.JButton jButtonUbicarProfesor;
  private javax.swing.JPanel jPanelAlumno;
  private javax.swing.JPanel jPanelAsignatura;
  private javax.swing.JPanel jPanelCursada;
  private javax.swing.JPanel jPanelProfesor;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextPane jTextPane1;
  // End of variables declaration//GEN-END:variables
}
