
package vista;

import excepciones.ClaveYaExistenteException;
import excepciones.DatoInvalidoException;
import excepciones.NoEncontradoException;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.HeadlessException;

import java.util.Iterator;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import modelo.Alumno;
import modelo.Asignatura;

/**
 *
 * @author wence
 */
public class Ventana
  extends javax.swing.JFrame
  implements ListSelectionListener
{
  private Receptor receptor;
  private int accionAceptar = 0;
  private static final int NUEVO = 0;
  private static final int MODIFICAR = 1;

  /** Creates new form Ventana */
  public Ventana()
  {
    initComponents();
    this.setResizable(false);
    this.setTitle("Programa de Gestion de asignaturas");
    this.setVisible(true);
    this.jButtonAgregarHistoria.setEnabled(false);
    this.jButtonAceptar.setEnabled(false);
    this.jButtonCancelar.setEnabled(false);
    this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    this.addWindowListener(new WindowAdapter()
    {

      @Override
      public void windowClosing(WindowEvent e)
      {
        super.windowClosing(e);
        Ventana.this.receptor.guardar();
        Ventana.this.dispose();
      }
    });
    this.jTableAlumno
        .getSelectionModel()
        .addListSelectionListener(this);
  }

  public void setReceptor(Receptor receptor)
  {
    this.receptor = receptor;
  }

  @Override
  public void valueChanged(ListSelectionEvent e)
  {
    Alumno elemento;
    try
    {
      elemento =
        (Alumno) this.receptor.buscar(this.jTableAlumno.getValueAt(this.jTableAlumno.getSelectedRow(), 0),
                                      Receptor.ALUMNO);
      this.jTextFieldLegajo.setText(elemento.getLegajo());
      this.jTextFieldNombre.setText(elemento.getApellidoNombre());
      this.jTextFieldDomicilio.setText(elemento.getDomicilio());
      this.jTextFieldMail.setText(elemento.getMail());

      Iterator<Asignatura> asignaturas = this.receptor.ubicar(this.jTextFieldBuscar.getText(), Receptor.ASIGNATURA);
      Asignatura aux;
      DefaultTableModel model = (DefaultTableModel) this.jTableHistoria.getModel();
      int n = model.getRowCount();
      int i;
      for (i = n; i > 0; i--)
        model.removeRow(i);
      while (asignaturas.hasNext())
      {
        aux = asignaturas.next();
        model.addRow(new Object[] { aux.getIdentificacion(), aux.getNombre() });
      }
      this.jTableHistoria.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
      this.jTableHistoria.setRowSelectionAllowed(true);
    }
    catch (NoEncontradoException f)
    {
    }
    catch (ArrayIndexOutOfBoundsException g)
    {
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents()//GEN-BEGIN:initComponents
  {

    jDialog1 = new javax.swing.JDialog();
    jDialog2 = new javax.swing.JDialog();
    jDialog3 = new javax.swing.JDialog();
    jDialog4 = new javax.swing.JDialog();
    jTabbedPane = new javax.swing.JTabbedPane();
    jPanelProfesor = new javax.swing.JPanel();
    jPanelAsignatura = new javax.swing.JPanel();
    jPanelCursada = new javax.swing.JPanel();
    jPanelAlumno = new javax.swing.JPanel();
    jPanelBuscar = new javax.swing.JPanel();
    jButtonBuscar = new javax.swing.JButton();
    jTextFieldBuscar = new javax.swing.JTextField();
    jPanel1 = new javax.swing.JPanel();
    jScrollPane3 = new javax.swing.JScrollPane();
    jTableAlumno = new javax.swing.JTable();
    jPanelResultados = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jTextFieldLegajo = new javax.swing.JTextField();
    jTextFieldNombre = new javax.swing.JTextField();
    jTextFieldDomicilio = new javax.swing.JTextField();
    jTextFieldMail = new javax.swing.JTextField();
    jScrollPane4 = new javax.swing.JScrollPane();
    jTableHistoria = new javax.swing.JTable();
    jButtonNuevo = new javax.swing.JButton();
    jButtonEliminar = new javax.swing.JButton();
    jButtonAgregarHistoria = new javax.swing.JButton();
    jButtonAceptar = new javax.swing.JButton();
    jButtonCancelar = new javax.swing.JButton();
    jButtonModificar = new javax.swing.JButton();
    jButtonAgradecimientos = new javax.swing.JButton();

    javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
    jDialog1.getContentPane().setLayout(jDialog1Layout);
    jDialog1Layout.setHorizontalGroup(
      jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    jDialog1Layout.setVerticalGroup(
      jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
    jDialog2.getContentPane().setLayout(jDialog2Layout);
    jDialog2Layout.setHorizontalGroup(
      jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    jDialog2Layout.setVerticalGroup(
      jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
    jDialog3.getContentPane().setLayout(jDialog3Layout);
    jDialog3Layout.setHorizontalGroup(
      jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    jDialog3Layout.setVerticalGroup(
      jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
    jDialog4.getContentPane().setLayout(jDialog4Layout);
    jDialog4Layout.setHorizontalGroup(
      jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    jDialog4Layout.setVerticalGroup(
      jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    javax.swing.GroupLayout jPanelProfesorLayout = new javax.swing.GroupLayout(jPanelProfesor);
    jPanelProfesor.setLayout(jPanelProfesorLayout);
    jPanelProfesorLayout.setHorizontalGroup(
      jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 1111, Short.MAX_VALUE)
    );
    jPanelProfesorLayout.setVerticalGroup(
      jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 458, Short.MAX_VALUE)
    );

    jTabbedPane.addTab("Profesor", jPanelProfesor);

    javax.swing.GroupLayout jPanelAsignaturaLayout = new javax.swing.GroupLayout(jPanelAsignatura);
    jPanelAsignatura.setLayout(jPanelAsignaturaLayout);
    jPanelAsignaturaLayout.setHorizontalGroup(
      jPanelAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 1111, Short.MAX_VALUE)
    );
    jPanelAsignaturaLayout.setVerticalGroup(
      jPanelAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 458, Short.MAX_VALUE)
    );

    jTabbedPane.addTab("Asignatura", jPanelAsignatura);

    javax.swing.GroupLayout jPanelCursadaLayout = new javax.swing.GroupLayout(jPanelCursada);
    jPanelCursada.setLayout(jPanelCursadaLayout);
    jPanelCursadaLayout.setHorizontalGroup(
      jPanelCursadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 1111, Short.MAX_VALUE)
    );
    jPanelCursadaLayout.setVerticalGroup(
      jPanelCursadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 458, Short.MAX_VALUE)
    );

    jTabbedPane.addTab("Cursada", jPanelCursada);

    jPanelAlumno.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jPanelBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jButtonBuscar.setText("Buscar");
    jButtonBuscar.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonBuscarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
    jPanelBuscar.setLayout(jPanelBuscarLayout);
    jPanelBuscarLayout.setHorizontalGroup(
      jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelBuscarLayout.createSequentialGroup()
        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanelBuscarLayout.setVerticalGroup(
      jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(jButtonBuscar))
    );

    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jTableAlumno.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {

      },
      new String []
      {
        "Legajo", "Apellido y Nombre", "Domicilio", "Mail"
      }
    )
    {
      Class[] types = new Class []
      {
        java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean []
      {
        false, false, false, false
      };

      public Class getColumnClass(int columnIndex)
      {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex)
      {
        return canEdit [columnIndex];
      }
    });
    jScrollPane3.setViewportView(jTableAlumno);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        .addContainerGap())
    );

    jPanelResultados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel1.setText("Legajo");

    jLabel3.setText("Apellido y Nombre");

    jLabel4.setText("Domicilio");

    jLabel5.setText("Mail");

    jLabel6.setText("Historia:");

    jTextFieldLegajo.setEditable(false);
    jTextFieldLegajo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jTextFieldNombre.setEditable(false);
    jTextFieldNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jTextFieldDomicilio.setEditable(false);
    jTextFieldDomicilio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jTextFieldMail.setEditable(false);
    jTextFieldMail.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jTableHistoria.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {

      },
      new String []
      {
        "Identificador", "Nombre"
      }
    )
    {
      Class[] types = new Class []
      {
        java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean []
      {
        false, false
      };

      public Class getColumnClass(int columnIndex)
      {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex)
      {
        return canEdit [columnIndex];
      }
    });
    jScrollPane4.setViewportView(jTableHistoria);

    jButtonNuevo.setText("Nuevo");
    jButtonNuevo.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonNuevoActionPerformed(evt);
      }
    });

    jButtonEliminar.setText("Eliminar");
    jButtonEliminar.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonEliminarActionPerformed(evt);
      }
    });

    jButtonAgregarHistoria.setText("Agregar...");
    jButtonAgregarHistoria.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonAgregarHistoriaActionPerformed(evt);
      }
    });

    jButtonAceptar.setText("Aceptar");
    jButtonAceptar.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonAceptarActionPerformed(evt);
      }
    });

    jButtonCancelar.setText("Cancelar");
    jButtonCancelar.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonCancelarActionPerformed(evt);
      }
    });

    jButtonModificar.setText("Modificar");
    jButtonModificar.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButtonModificarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanelResultadosLayout = new javax.swing.GroupLayout(jPanelResultados);
    jPanelResultados.setLayout(jPanelResultadosLayout);
    jPanelResultadosLayout.setHorizontalGroup(
      jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelResultadosLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane4)
          .addGroup(jPanelResultadosLayout.createSequentialGroup()
            .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jLabel1)
              .addComponent(jLabel4)
              .addComponent(jLabel5)
              .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jTextFieldMail, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
              .addComponent(jTextFieldLegajo, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jTextFieldDomicilio)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultadosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonAgregarHistoria))))
          .addGroup(jPanelResultadosLayout.createSequentialGroup()
            .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanelResultadosLayout.createSequentialGroup()
                .addComponent(jButtonAceptar)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelar))
              .addGroup(jPanelResultadosLayout.createSequentialGroup()
                .addComponent(jButtonNuevo)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminar)
                .addGap(18, 18, 18)
                .addComponent(jButtonModificar)))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanelResultadosLayout.setVerticalGroup(
      jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelResultadosLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButtonNuevo)
          .addComponent(jButtonEliminar)
          .addComponent(jButtonModificar))
        .addGap(18, 18, 18)
        .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jTextFieldLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jTextFieldDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanelResultadosLayout.createSequentialGroup()
            .addComponent(jLabel6)
            .addGap(18, 18, 18))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultadosLayout.createSequentialGroup()
            .addComponent(jButtonAgregarHistoria)
            .addGap(2, 2, 2)))
        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButtonAceptar)
          .addComponent(jButtonCancelar))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanelAlumnoLayout = new javax.swing.GroupLayout(jPanelAlumno);
    jPanelAlumno.setLayout(jPanelAlumnoLayout);
    jPanelAlumnoLayout.setHorizontalGroup(
      jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelAlumnoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addComponent(jPanelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    jPanelAlumnoLayout.setVerticalGroup(
      jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelAlumnoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jPanelAlumnoLayout.createSequentialGroup()
            .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );

    jTabbedPane.addTab("Alumno", jPanelAlumno);

    jButtonAgradecimientos.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
    jButtonAgradecimientos.setText("Agradecimientos");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPane)
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(jButtonAgradecimientos))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jButtonAgradecimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jTabbedPane)
        .addContainerGap())
    );

    pack();
  }//GEN-END:initComponents

  private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarActionPerformed
  {//GEN-HEADEREND:event_jButtonBuscarActionPerformed
    try
    {
      Iterator<Alumno> alumnos = this.receptor.ubicar(this.jTextFieldBuscar.getText(), Receptor.ALUMNO);
      Alumno aux;
      DefaultTableModel model = (DefaultTableModel) this.jTableAlumno.getModel();
      model.setRowCount(0);
      while (alumnos.hasNext())
      {
        aux = alumnos.next();
        model.addRow(new Object[] { aux.getLegajo(), aux.getApellidoNombre(), aux.getDomicilio(), aux.getMail() });
      }
    }
    catch (NoEncontradoException e)
    {
      JOptionPane.showMessageDialog(this, e.getMessage() + ", por favor vuelva a ingresarlo");
    }
  }//GEN-LAST:event_jButtonBuscarActionPerformed

  private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonNuevoActionPerformed
  {//GEN-HEADEREND:event_jButtonNuevoActionPerformed
    this.accionAceptar = Ventana.NUEVO;
    this.jButtonEliminar.setEnabled(false);
    this.jButtonModificar.setEnabled(false);
    this.jButtonAgregarHistoria.setEnabled(true);
    this.jButtonCancelar.setEnabled(true);
    this.jTextFieldNombre.setEditable(true);
    this.jTextFieldDomicilio.setEditable(true);
    this.jButtonAceptar.setEnabled(true);
    this.jTextFieldMail.setEditable(true);
    this.jTextFieldLegajo.setText("");
    this.jTextFieldNombre.setText("");
    this.jTextFieldDomicilio.setText("");
    this.jTextFieldMail.setText("");
  }//GEN-LAST:event_jButtonNuevoActionPerformed

  private void jButtonAgregarHistoriaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAgregarHistoriaActionPerformed
  {//GEN-HEADEREND:event_jButtonAgregarHistoriaActionPerformed
    new DialogAsignatura(this.receptor, this.jTableHistoria, new TableModelAsignatura());  
  }//GEN-LAST:event_jButtonAgregarHistoriaActionPerformed

  private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonModificarActionPerformed
  {//GEN-HEADEREND:event_jButtonModificarActionPerformed
    if (!this.jTextFieldLegajo
             .getText()
             .equals(""))
    {
      this.jTextFieldNombre.setEditable(true);
      this.jTextFieldDomicilio.setEditable(true);
      this.jTextFieldMail.setEditable(true);
      this.jButtonAgregarHistoria.setEnabled(true);
      this.jButtonEliminar.setEnabled(true);
      this.jButtonNuevo.setEnabled(true);
      this.jButtonAceptar.setEnabled(true);
      this.jButtonCancelar.setEnabled(true);
      this.accionAceptar = Ventana.MODIFICAR;
    }
    else
      JOptionPane.showMessageDialog(this, "Seleccione un alumno para poder modificarlo");
   
  }//GEN-LAST:event_jButtonModificarActionPerformed

  private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonEliminarActionPerformed
  {//GEN-HEADEREND:event_jButtonEliminarActionPerformed
    if (!this.jTextFieldLegajo
             .getText()
             .equals(""))
    {
      try
      {
        this.receptor.baja(this.jTextFieldLegajo.getText(), Receptor.ALUMNO);
      }
      catch (NoEncontradoException e)
      {
        JOptionPane.showMessageDialog(this, e.getMessage());
      }
    }
    else
      JOptionPane.showMessageDialog(this, "Seleccione un alumno para poder eliminarlo");
  }//GEN-LAST:event_jButtonEliminarActionPerformed

  private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelarActionPerformed
  {//GEN-HEADEREND:event_jButtonCancelarActionPerformed
    this.jTextFieldLegajo.setText("");
    this.jTextFieldNombre.setText("");
    this.jTextFieldNombre.setEditable(false);
    this.jTextFieldDomicilio.setText("");
    this.jTextFieldDomicilio.setEditable(false);
    this.jTextFieldMail.setText("");
    this.jTextFieldMail.setEditable(false);
    this.jButtonAgregarHistoria.setEnabled(false);
    this.jButtonAceptar.setEnabled(false);
    this.jButtonEliminar.setEnabled(true);
    this.jButtonModificar.setEnabled(true);
    this.jButtonNuevo.setEnabled(true);
    this.jButtonCancelar.setEnabled(false);
  }//GEN-LAST:event_jButtonCancelarActionPerformed

  private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAceptarActionPerformed
  {//GEN-HEADEREND:event_jButtonAceptarActionPerformed
    
    switch (this.accionAceptar)
    {
      case Ventana.NUEVO:
        try
        {
          Alumno nuevo =
            new Alumno(this.jTextFieldNombre.getText(), this.jTextFieldDomicilio.getText(),
                       this.jTextFieldMail.getText());
          int n = this.jTableHistoria.getRowCount();
          int i;
          Asignatura elemento;
          for (i = 1; i <= n; i++)
          {
            elemento = (Asignatura) this.receptor.buscar(this.jTableHistoria.getValueAt(i, 0), Receptor.ASIGNATURA);
            nuevo.agregarHistoria(elemento);
          }
          this.receptor.alta(nuevo, Receptor.ALUMNO);
          this.jButtonCancelarActionPerformed(evt);
        }
        catch (NoEncontradoException | ClaveYaExistenteException | DatoInvalidoException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());
        }
        break;
      case Ventana.MODIFICAR:
        try
        {
          Alumno modif =
            new Alumno(this.jTextFieldNombre.getText(), this.jTextFieldDomicilio.getText(),
                       this.jTextFieldMail.getText());
          int n = this.jTableHistoria.getRowCount();
          int i;
          Asignatura elemento;
          for (i = 1; i <= n; i++)
          {
            elemento = (Asignatura) this.receptor.buscar(this.jTableHistoria.getValueAt(i, 0), Receptor.ASIGNATURA);
            modif.agregarHistoria(elemento);
          }
          modif.setLegajo(this.jTextFieldLegajo.getText());
          this.receptor.modificacion(modif, Receptor.ALUMNO);
          this.jButtonCancelarActionPerformed(evt);
        }
        catch (DatoInvalidoException | NoEncontradoException | ClaveYaExistenteException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());
        }
        break;
    }
    
    
  }//GEN-LAST:event_jButtonAceptarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info: javax.swing
                                                            .UIManager
                                                            .getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing
               .UIManager
               .setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util
          .logging
          .Logger
          .getLogger(Ventana.class.getName())
          .log(java.util
                   .logging
                   .Level
                   .SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util
          .logging
          .Logger
          .getLogger(Ventana.class.getName())
          .log(java.util
                   .logging
                   .Level
                   .SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util
          .logging
          .Logger
          .getLogger(Ventana.class.getName())
          .log(java.util
                   .logging
                   .Level
                   .SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util
          .logging
          .Logger
          .getLogger(Ventana.class.getName())
          .log(java.util
                   .logging
                   .Level
                   .SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonAceptar;
  private javax.swing.JButton jButtonAgradecimientos;
  private javax.swing.JButton jButtonAgregarHistoria;
  private javax.swing.JButton jButtonBuscar;
  private javax.swing.JButton jButtonCancelar;
  private javax.swing.JButton jButtonEliminar;
  private javax.swing.JButton jButtonModificar;
  private javax.swing.JButton jButtonNuevo;
  private javax.swing.JDialog jDialog1;
  private javax.swing.JDialog jDialog2;
  private javax.swing.JDialog jDialog3;
  private javax.swing.JDialog jDialog4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanelAlumno;
  private javax.swing.JPanel jPanelAsignatura;
  private javax.swing.JPanel jPanelBuscar;
  private javax.swing.JPanel jPanelCursada;
  private javax.swing.JPanel jPanelProfesor;
  private javax.swing.JPanel jPanelResultados;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JTabbedPane jTabbedPane;
  private javax.swing.JTable jTableAlumno;
  private javax.swing.JTable jTableHistoria;
  private javax.swing.JTextField jTextFieldBuscar;
  private javax.swing.JTextField jTextFieldDomicilio;
  private javax.swing.JTextField jTextFieldLegajo;
  private javax.swing.JTextField jTextFieldMail;
  private javax.swing.JTextField jTextFieldNombre;
  // End of variables declaration//GEN-END:variables
}
